# Import Library

In [1]:
# Install library Sastrawi
!pip install PySastrawi

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes


In [2]:
import pandas as pd  
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
import re
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelBinarizer
from sklearn.feature_selection import SelectKBest, chi2
import numpy as np

# Membaca data hasil crawling

In [3]:
data = pd.read_csv('dataset_PTA.csv')
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_PTA.csv'

In [4]:
data.shape

(60, 3)

In [5]:
# Inisialisasi label (Bidang Minat) ke dalam array
y = [ y[0] for y in data.iloc[:, [2]].values ]

In [6]:
print(y)

['CAI', 'RPL', 'RPL', 'CAI', 'CAI', 'RPL', 'CAI', 'CAI', 'CAI', 'CAI', 'RPL', 'CAI', 'RPL', 'RPL', 'CAI', 'CAI', 'CAI', 'CAI', 'CAI', 'CAI', 'RPL', 'CAI', 'CAI', 'RPL', 'CAI', 'CAI', 'RPL', 'RPL', 'CAI', 'RPL', 'RPL', 'CAI', 'RPL', 'RPL', 'RPL', 'RPL', 'CAI', 'RPL', 'RPL', 'RPL', 'CAI', 'RPL', 'CAI', 'CAI', 'RPL', 'RPL', 'RPL', 'RPL', 'RPL', 'CAI', 'RPL', 'RPL', 'RPL', 'RPL', 'RPL', 'CAI', 'CAI', 'RPL', 'CAI', 'RPL']


In [7]:
# Inisialisasi abstraksi ke dalam array
x = [ w[0] for w in data.iloc[:, [1]].values ]

In [8]:
x[0]

'Gerak pekerja ada pada game yang memiliki genre RTS (Real-Time Strategy). Gerak pekerja memiliki berbagai macam gerak. Oleh sebab itu dibutuhkan sebuah pendekatan konsep AI  untuk mendesain perilaku pekerja tersebut. Perilaku karakter tersebut harus ditambahi dengan AI (Artifical intelegent) agar perilakunya menjadi lebih hidup dan realistis.\nDalam penelitian ini AI yang digunakan adalah Finite State Machine. Finite State Machine digunakan untuk menentukan gerak pekerja terhadap parameter-parameter yang digunakan sebagai dasar gerak yang akan dilakukan . Selanjutnya akan disimulasikan pada game RTS dengan menggunakan game engine.\nHasil yang di peroleh dalam penelitian ini adalah penerapan metode Finite State machine untuk menentukan gerak pekerja berdasarkan parameter jumlah harta, prajurit, kondisi bangunan, dan stockpile (jumlah resources yang di bawa). \n\nKata kunci : Game, Real-Time Strategy, Gerak Pekerja, Finite State Machine.\n'

# Preprocessing Data Teks

## Case Folding dan menghapus karakter yang tidak diperlukan

In [9]:
for i in range(len(x)):
    # Mengubah teks menjadi lowercase
    x[i] = x[i].lower()
    
    # Menghapus angka
    x[i] = re.sub(r"\d+", "", x[i])
    
    # Menghapus white space
    x[i] = x[i].strip()
    
    # Menghapus tanda baca
    x[i] = x[i].translate(str.maketrans("","",string.punctuation))

In [10]:
x[0]

'gerak pekerja ada pada game yang memiliki genre rts realtime strategy gerak pekerja memiliki berbagai macam gerak oleh sebab itu dibutuhkan sebuah pendekatan konsep ai  untuk mendesain perilaku pekerja tersebut perilaku karakter tersebut harus ditambahi dengan ai artifical intelegent agar perilakunya menjadi lebih hidup dan realistis\ndalam penelitian ini ai yang digunakan adalah finite state machine finite state machine digunakan untuk menentukan gerak pekerja terhadap parameterparameter yang digunakan sebagai dasar gerak yang akan dilakukan  selanjutnya akan disimulasikan pada game rts dengan menggunakan game engine\nhasil yang di peroleh dalam penelitian ini adalah penerapan metode finite state machine untuk menentukan gerak pekerja berdasarkan parameter jumlah harta prajurit kondisi bangunan dan stockpile jumlah resources yang di bawa \n\nkata kunci  game realtime strategy gerak pekerja finite state machine'

## Stemming dan stopwords removal menggunakan Sastrawi

In [11]:
# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Create stopwordremover
factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

for i in range(len(x)):
    # Stemming
    x[i] = stemmer.stem(x[i])
    
    # Hapus Stopword
    x[i] = stopword.remove(x[i])

In [12]:
x[0]

'gerak game milik genre rts realtime strategy gerak milik gerak butuh buah konsep ai desain perilaku perilaku karakter ai artifical intelegent perilaku hidup realistis teliti ai finite state machine finite state machine gerak parameterparameter dasar gerak simulasi game rts game engine hasil teliti terap metode finite state machine gerak dasar parameter harta prajurit kondisi bangun stockpile resources bawa kunci game realtime strategy gerak finite state machine'

In [13]:
vect = CountVectorizer()

data_tf = vect.fit_transform(x)
data_tf = data_tf.toarray()

x_dtm = pd.DataFrame(data_tf, columns = vect.get_feature_names_out())
x_dtm.head()

abstrak  actor  acu  acute  adadari  adaptive  adat  addie  additive  adm  \
0        0      0    0      0        0         0     0      0         0    0   
1        0      0    0      0        0         0     0      0         0    2   
2        0      0    0      0        0         0     0      0         0    0   
3        0      0    0      0        0         0     0      0         0    0   
4        0      0    0      0        0         0     0      0         0    0   

   ...  weighting  weights  weightsaw  wewenangannya  wiener  wilayah  winqsb  \
0  ...          0        0          0              0       0        0       0   
1  ...          0        0          0              0       0        0       0   
2  ...          0        0          0              0       0        0       0   
3  ...          0        0          0              0       0        0       0   
4  ...          0        0          0              0       0        0       0   

   wisatawan  workshop  xbox  
0          0         0     0  
1          0         0     0  
2          0         0     0  
3          0         0     0  
4          0         0     0  

[5 rows x 1336 columns]

# Seleksi Fitur

## Menghitung nilai chi-square manual

In [14]:
# binarisasi kolom output
y_binarized = LabelBinarizer().fit_transform(y)
print(y_binarized.T)

# baris menunjukkan jumlah pengamatan setiap kelas
# dan kolom menunjukkan setiap fitur
observed = np.dot(y_binarized.T, x_dtm)
print(observed)

[[0 1 1 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1
  0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1]]
[[2 1 2 ... 1 1 1]]


In [15]:
# menghitung probabilitas setiap kelas dan jumlah fitur; 
# simpan keduanya sebagai array dua dimensi dengan menggunakan reshape
class_prob = y_binarized.mean(axis = 0).reshape(1, -1)
feature_count = x_dtm.to_numpy().sum(axis = 0).reshape(1, -1)
expected = np.dot(class_prob.T, feature_count)

print(expected)

[[1.06666667 0.53333333 1.6        ... 0.53333333 0.53333333 0.53333333]]


In [16]:
chisq = (observed - expected) ** 2 / expected
chisq_score = chisq.sum(axis = 0)
print(chisq_score)

[0.81666667 0.40833333 0.1        ... 0.40833333 0.40833333 0.40833333]


## Menghitung nilai chi-square menggunakan fungsi dari sklearn

In [17]:
# Menghitung nilai chi-square menggunakan fungsi chi2
chi2score = chi2(x_dtm, y)

skorchi= np.reshape(chi2score[1], (1, chi2score[0].shape[0]))

In [18]:
# Menampilkan nilai chi-square dalam bentuk DataFrame
data_skorchi = pd.DataFrame(skorchi, columns = vect.get_feature_names_out())
data_skorchi

abstrak     actor       acu     acute   adadari  adaptive      adat  \
0  0.185877  0.349575  0.643429  0.064078  0.285049   0.13057  0.349575   

      addie  additive       adm  ...  weighting   weights  weightsaw  \
0  0.185877  0.085932  0.185877  ...   0.105193  0.349575   0.185877   

   wewenangannya   wiener   wilayah    winqsb  wisatawan  workshop      xbox  
0       0.349575  0.13057  0.285049  0.064078   0.349575  0.349575  0.349575  

[1 rows x 1336 columns]

In [19]:
# Mencari 50 kata yang paling relevan dalam menentukan bidang minat
kbest = SelectKBest(score_func = chi2, k = 10)

X_dtm_kbest = kbest.fit_transform(x_dtm, y)
mask = kbest.get_support()

X_dtm_kbest = x_dtm.columns[mask]
X_dtm_kbest

Index(['ajar', 'akademik', 'akurasi', 'algoritma', 'amal', 'android',
       'anggota', 'aplikasi', 'bahasa', 'bayes', 'beasiswa', 'calon', 'citra',
       'cluster', 'clustering', 'distance', 'dosen', 'dukung', 'ekstraksi',
       'fitur', 'game', 'giat', 'gizi', 'guru', 'informasi', 'kelola',
       'kmeans', 'komponen', 'kredit', 'lahan', 'lapor', 'madura', 'main',
       'media', 'metode', 'mobile', 'mudah', 'na', 'organisasi', 'putus',
       'resiko', 'sakit', 'siswa', 'tani', 'teknik', 'teknologi', 'terima',
       'topsis', 've', 'wajah'],
      dtype='object')

In [20]:
# Menampilkan 10 term paling relevan dan menambahkan kolom "Bidang Minat"
result = pd.concat([x_dtm[X_dtm_kbest], data["Bidang Minat"]], axis=1)
result.head()

ajar  akademik  akurasi  algoritma  amal  android  anggota  aplikasi  \
0     0         0        0          0     0        0        0         0   
1     0         0        0          0     0        0        0         1   
2     3         0        0          0     0        6        0         4   
3     0         0        0          0     0        0        0         0   
4     0         0        1          0     0        0        0         2   

   bahasa  bayes  ...  sakit  siswa  tani  teknik  teknologi  terima  topsis  \
0       0      0  ...      0      0     0       0          0       0       0   
1       0      0  ...      0      0     0       0          2       0       0   
2       2      0  ...      0      0     0       0          6       0       0   
3       0      0  ...      0      0     0       0          0       0       0   
4       0      3  ...      2      0     0       0          0       0       0   

   ve  wajah  Bidang Minat  
0   0      0           CAI  
1   0      0           RPL  
2   0      0           RPL  
3   0      0           CAI  
4   3      0           CAI  

[5 rows x 51 columns]

In [21]:
result.to_csv("Hasil_Seleksi_Fitur.csv", index=False)